db_info  = {
    "lcls-dev3":{
        "file_paths":{
            "config":"/afs/slac/g/lcls/physics/mps_configuration/current",
            "history":"/u/cd/lking/mps/mps_history",
            "runtime":"/u1/lcls/physics/mps_manager"
        },
        "file_names":{
            "config":"mps_config-2021-09-20-a.db",
            "history":None,
            "runtime":None
        },
        "logger":{
            "log_directory":"/u/cd/lking/mps/mps_logs/mps_history"
        }
    },
    "test":{
        "file_paths":{
            "config":None,
            "history":None,
            "runtime":None
        },
        "file_names":{
            "config":"mps_config_imported.db",
            "history":"mps_gun_history.db",
            "runtime":None
        },
        "logger":{
            "log_directory":"/Users/lking/Documents/Projects/mps_database/test_logs/mps_history-"
        }
    },
    "prod":
    {
        "file_paths":{
            "config":"",
            "history":"",
            "runtime":""
        },
        "file_names":{
            "config":"",
            "history":None,
            "runtime":None
        },
        "logger":{
            "log_directory":""
        }
    },

}