apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: application-secrets
spec:
  path: secret/ad/accel-webapp-dev/mps-history/application-secrets
  type: Opaque
  keys:
    - ELOG_HISTORY_LOGBOOK_ID
    - ELOG_USER_PASSWORD
    - KAFKA_PASSWORD
    - KAFKA_BOOTSTRAP_SERVER
